blog:
    pattern:  /
    defaults: { _controller: jidefaultBundle:Blog:index }

blog_edit:
    pattern:  /edit/{blog}
    defaults: { _controller: jidefaultBundle:Blog:edit }

blog_delete:
    pattern:  /delete/{blog}
    defaults: { _controller: jidefaultBundle:Blog:delete }

blog_add:
    pattern:  /add
    defaults: { _controller: jidefaultBundle:Blog:add }
