joindinUserBundle:
    resource: "@joindinUserBundle/Resources/config/routing.yml"
    prefix:   /

# Talk specific pages
joindinTalkBundle:
    resource: "@joindinTalkBundle/Resources/config/routing.yml"
    prefix:   /talk

# Event specific pages
joindinEventBundle:
    resource: "@joindinEventBundle/Resources/config/routing.yml"
    prefix:   /event

# Blog pages
joindinBlogBundle:
    resource: "@joindinBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

# User specific pages
joindinUserBundle:
    resource: "@joindinUserBundle/Resources/config/routing.yml"
    prefix:   /user

# Static pages and homepage
joindindefaultBundle:
    resource: "@joindindefaultBundle/Resources/config/routing.yml"
    prefix:   /

event_quicklink:
    pattern:  /{id}
    defaults: { _controller: joindinEventBundle:View:index }
    requirements:
        id:  \d+

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
