joindinEventBundle_main:
    pattern:  /
    defaults: { _controller: joindinEventBundle:Default:index }

joindinEventBundle_defaults:
    resource: "@joindinEventBundle/Resources/config/routes/default.yml"
    prefix:   /

joindinEventBundle_views:
    resource: "@joindinEventBundle/Resources/config/routes/view.yml"
    prefix:   /

joindinEventBundle_attendees:
    resource: "@joindinEventBundle/Resources/config/routes/attendees.yml"
    prefix:   /

joindinEventBundle_submit:
    resource: "@joindinEventBundle/Resources/config/routes/submit.yml"
    prefix:   /