joindinEventBundle_hot_events:
    pattern:  /event/hot
    defaults: { _controller: joindinEventBundle:Default:hot }

joindinEventBundle_upcoming_events:
    pattern:  /event/upcoming
    defaults: { _controller: joindinEventBundle:Default:upcoming }

joindinEventBundle_all_events:
    pattern:  /event/all
    defaults: { _controller: joindinEventBundle:Default:all }

joindinEventBundle_upcoming_past:
    pattern:  /event/past
    defaults: { _controller: joindinEventBundle:Default:past }
