home:
    pattern:  /
    defaults: { _controller: joindindefaultBundle:Default:index }

help:
    resource: "@joindindefaultBundle/Resources/config/routes/help.yml"
    prefix:   /help

about:
    resource: "@joindindefaultBundle/Resources/config/routes/about.yml"
    prefix:   /about

contact:
    resource: "@joindindefaultBundle/Resources/config/routes/contact.yml"
    prefix:   /about/contact