joindinEventBundle_hot_events:
    pattern:  /hot
    defaults: { _controller: joindinEventBundle:Default:hot }

joindinEventBundle_upcoming_events:
    pattern:  /upcoming
    defaults: { _controller: joindinEventBundle:Default:upcoming }

joindinEventBundle_all_events:
    pattern:  /all
    defaults: { _controller: joindinEventBundle:Default:all }

joindinEventBundle_past_events:
    pattern:  /past
    defaults: { _controller: joindinEventBundle:Default:past }

joindinEventBundle_callforpapers_events:
    pattern:  /callforpapers
    defaults: { _controller: joindinEventBundle:Default:callforpapers }

