parameters:
#    jidefault.example.class: ji\defaultBundle\Example

services:
#    jidefault.example:
#        class: %jidefault.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
